'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Jqgrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Jqgrid1 As Global.Trirand.Web.UI.WebControls.JQGrid

    '''<summary>
    '''LossLocationCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LossLocationCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LossLocationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LossLocationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LossDateCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LossDateCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LossDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LossDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LossTimeCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LossTimeCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LossTimeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LossTimeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''anchor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents anchor1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''img1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''PolicyNumberCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyNumberCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PolicyNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VehicleMakeCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehicleMakeCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VehicleMakeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehicleMakeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VehicleModelCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehicleModelCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VehicleModelLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehicleModelLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VINCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VINCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VINLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VINLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VehicleColorCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehicleColorCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VehicleColorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehicleColorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DeviceKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceKey As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DeviceKeyTextArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceKeyTextArea As Global.System.Web.UI.WebControls.TextBox
End Class
